# swagger.yml

openapi: 3.0.0
info:
  title: "Interface for Mondelez API client"
  description: "Just an Interface"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Customer:
      type: "object"
      

paths:
  /customer:
    get:
      operationId: "customer.list_all"
      tags:
        - "Customer"
      summary: "Read the list of Customer"
      responses:
        "200":
          description: "Successfully read customer list"
    post:
      operationId: "customer.create"
      tags:
        - Customer
      summary: "Create a customer"
      requestBody:
          description: "Customer to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "customer"
                $ref: "#/components/schemas/Customer"
      responses:
        "200":
          description: "Successfully created customer"