from resources.resource import Resource
from resources.catalog.product import Product
from resources.catalog.brand import Brand
from resources.catalog.category import Category
from resources.customer.customer import Customer
from resources.inventories.inventories import Inventories
from resources.tracking.tracking import Tracking
from resources.protocols.protocols import Protocols
from client import IntegraCommerceClient