from resources.resource import Resource
from resources.catalog import Product
from resources.catalog import Brand
from resources.catalog import Category
from resources.catalog import Supplier
from resources.customer import Customer
from resources.inventories.inventories import Inventories
from resources.tracking.tracking import Tracking
from resources.protocols.protocols import Protocols
from client import IntegraCommerceClient